/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    AsideButton: typeof import('./components/AsideButton.vue')['default']
    AsideMenu: typeof import('./components/AsideMenu.vue')['default']
    Button: typeof import('./components/form/Button.vue')['default']
    CheckboxInput: typeof import('./components/form/CheckboxInput.vue')['default']
    copy: typeof import('./components/form/TextInput copy.vue')['default']
    FadeTransition: typeof import('./components/transitions/FadeTransition.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinIcon: typeof import('./components/icons/LoadingSpinIcon.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    PasswordRequirements: typeof import('./components/PasswordRequirements.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextareaInput: typeof import('./components/form/TextareaInput.vue')['default']
    TextAreaInput: typeof import('./components/form/TextAreaInput.vue')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
  }
}
