/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    AsideButton: typeof import('./components/AsideButton.vue')['default']
    AsideDialog: typeof import('./components/AsideDialog.vue')['default']
    AsideMenu: typeof import('./components/AsideMenu.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    BasicCheckbox: typeof import('./components/form/BasicCheckbox.vue')['default']
    BasicSelect: typeof import('./components/form/BasicSelect.vue')['default']
    Button: typeof import('./components/form/Button.vue')['default']
    CheckboxInput: typeof import('./components/form/CheckboxInput.vue')['default']
    copy: typeof import('./components/form/TextInput copy.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    FadeTransition: typeof import('./components/transitions/FadeTransition.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LoadingSpinIcon: typeof import('./components/icons/LoadingSpinIcon.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PasswordRequirements: typeof import('./components/PasswordRequirements.vue')['default']
    PasswordStrength: typeof import('./components/PasswordStrength.vue')['default']
    ProfileMenu: typeof import('./components/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleTransition: typeof import('./components/transitions/ScaleTransition.vue')['default']
    TextareaInput: typeof import('./components/form/TextareaInput.vue')['default']
    TextAreaInput: typeof import('./components/form/TextAreaInput.vue')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    UsersTable: typeof import('./components/users/UsersTable.vue')['default']
  }
}
