name: Release nightly Docker image

on:
  push:
    branches:
      - main
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone repository (latest)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone repository (custom ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=nightly
            type=sha,prefix=,format=short,enable=${{ github.event.inputs.git-ref != '' }}
          labels: |
            org.opencontainers.image.title=Tankobon

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            NIGHTLY=true
