name: Tests

on:
  pull_request:
    paths-ignore:
      - 'client/locales/*'
      - '**.md'
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 19]
    name: Test server in JDK ${{ matrix.java }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          java-package: 'jdk'
          distribution: 'temurin'
      - name: Run build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-jdk-${{ matrix.java }}
          path: server/build/test-results/
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-jdk-${{ matrix.java }}
          path: server/build/reports/tests/

  test-client:
    runs-on: ubuntu-latest
    name: Test client
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/client/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        working-directory: client
        run: pnpm install
      - name: Run build
        working-directory: client
        run: pnpm build
      - name: Run tests
        working-directory: client
        run: pnpm test
