name: Tests

on:
  pull_request:
    paths-ignore:
      - 'client/locales/*'
      - '**.md'
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 19]
    name: Test server in JDK ${{ matrix.java }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          java-package: 'jdk'
          distribution: 'temurin'
      - name: Run build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-jdk-${{ matrix.java }}
          path: server/build/test-results/
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-jdk-${{ matrix.java }}
          path: server/build/reports/tests/

